version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - zoo.env
    networks:
      - wallet

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    networks:
      - wallet

  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      - wallet

  app:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - kafka
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - app.env
    networks:
      - wallet

networks:
  wallet:
    driver: bridge