version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - 'ZOOKEEPER_CLIENT_PORT=2181'
      - 'ZOOKEEPER_TICK_TIME=2000'
    networks:
      - wallet

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - 'KAFKA_BROKER_ID=1'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
    networks:
      - wallet

  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=walletdb'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - "5432:5432"
    networks:
      - wallet

  app:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - kafka
      - postgres
    ports:
      - "8080:8080"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/walletdb'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE_PASSWORD=password'
      - 'SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092'
    networks:
      - wallet

networks:
  wallet:
    driver: bridge