version: '1.0'
services:
  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      - wallet

  app:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - app.env
    networks:
      - wallet

networks:
  wallet:
    driver: bridge