version: '1.0'
services:
  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      - wallet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - wallet

  app:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - app.env
    networks:
      - wallet

networks:
  wallet:
    driver: bridge