spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        max.poll.interval.ms: 60000
      producer:
        retries: 3
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: DEBUG
    org.apache.kafka.clients.consumer.ConsumerConfig: DEBUG